### ISSUE TITLE
Too many resources

### ISSUE THREAD

**Issue by satyrlord** [StellarisPlus/stellarisplus#5]
A common side-effect of Colonize Unlimited is the presence of way to many resources everywhere. While it's fine to have more resources in vanilla, we have to tone some of the few numbers down somehow.

Suggestions:
* Toggle Vanilla / CU resources in galaxy generations
* Reduce number of resources

**Comment by dosaki** [comment]
Suggestions:
* Toggle Vanilla / CU resources in galaxy generations

**Comment by satyrlord** [comment]
I love your suggestion, sadly I have no idea how to implement it. Can you?

**Comment by dosaki** [comment]
Not entirely sure if it is at all possible, but I will try to see what I can do.
If not, this can be a request for Paradox:
* set parameters on galaxy creation
* enable/disable techs, resources, ships, etc depending on parameters

**Comment by satyrlord** [comment]
@dosaki is the owner for Colonize Unlimited, including the extra resources. He will make the final call and the team must accept it.

**Comment by dosaki** [comment]
@Thomahawk2's decision too

**Comment by dosaki** [comment]
Reduced the number of terraforming resources from 6 to 4.
Terraforming may need some rebalancing.

This will make will old saves using this mod (or Colonize Unlimited) incompatible with this version.

**Comment by satyrlord** [comment]
I started some new games yesterday for testing purposes and there's still a shit ton of resources (minerals, power, science) being generated everywhere, like nothing's changed. Can this be still reduced further? I know more colonizable planets automatically bring more resources, but there has to be a way to reduce the probability that a planet has a resource in orbit.

**Comment by satyrlord** [comment]
Nevermind, I found it in 00_deposits.txt. I will start testing various configurations.

**Comment by dosaki** [comment]
Good call.

I'm on holidays so I don't have much time to tweak the values.
On 19 Jun 2016 12:52 p.m., "Razvan Petrescu" <notifications@github.com>
wrote:

Nevermind, I found it in 00_deposits.txt. I will start testing various
configurations.

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
<https://github.com/StellarisPlus/stellarisplus/issues/5#issuecomment-226993306>,
or mute the thread
<https://github.com/notifications/unsubscribe/AB3eSu_Xxo-K4O_pr5zv30HmdHOFdDBAks5qNS2FgaJpZM4IuISu>
.
